# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-19 23:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='description',
            old_name='desc',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='description',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='first_app.Course'),
        ),
    ]
